### PR TITLE
Mqa gqa bugfix

### PR DESCRIPTION
**Pull request by vgokhale**
Fix KV head index calculation for MQA / GQA.

Also made HQ and HK constexprs to increase performance by a bit.

### CODE REVIEW

**Review by micmelesse — COMMENTED** [review]
I ran the forward test and I get this

``` ========================================================================== short test summary info ===========================================================================
FAILED python/perf-kernels/flash-attention.py::test_op_fwd[True-False-4-4-4-128-128-65] - AssertionError: Tensor-likes are not close!

Mismatched elements: 133120 / 133120 (100.0%)
Greatest absolute difference: nan at index (0, 0, 0, 0) (up to 0.02 allowed)
Greatest relative difference: nan at index (0, 0, 0, 0) (up to 0.02 allowed)
FAILED python/perf-kernels/flash-attention.py::test_op_fwd[False-True-4-4-1-1024-1024-33] - AssertionError: Tensor-likes are not close!

Mismatched elements: 540672 / 540672 (100.0%)
Greatest absolute difference: nan at index (0, 0, 0, 0) (up to 0.02 allowed)
Greatest relative difference: nan at index (0, 0, 0, 0) (up to 0.02 allowed)
================================================================== 2 failed, 62 passed in 244.79s (0:04:04) ==================================================================
```

**Comment by vgokhale** [comment]
> I ran the forward test on our MI300 machine and I get this. Is this expected?

That is odd. I am unable to reproduce this. I'll try a different container....

**Comment by vgokhale** [comment]
This looks like some kind on instability in the compiler. It only happens if this autotune config is picked:

`triton.Config({'BLOCK_M': 128, 'BLOCK_N': 64, 'waves_per_eu': 3, 'PRE_LOAD_V': False}, num_stages=1, num_warps=4),`

And even then only on some input shapes where the head_size is not a multiple of 64 (both fails here are 65) but not all cases with head_size 65 and this autotune config. I will investigate more...

**Comment by vgokhale** [comment]
Ok it's fixed. Appreciate the scrutiny Michael!

**Review by hongxiayang — APPROVED** [review]
Thanks for the fix. I verified and integrated to vllm.

**Pull request merged**
