### PR TITLE
Update tune_gemm.py to save benchmarking results in a file

### PR DESCRIPTION
**Pull request by yiqian1**
-Update tune_gemm.py to save benchmarking results in a file. 
-Append the tuning or benchmarking results to an output file. This is because the run_triton scripts in msft_amd_ai_operators tune the gemm configurations one by one, and I'd like to save all tuning results in one single file so that I can use it to benchmark tuned configs all at once.

This change is a prerequisite for [this PR](https://github.com/ROCm/msft_amd_ai_operators/pull/367).

### CODE REVIEW

**Comment by zhanglx13** [comment]
Why do we need to save benchmark results in a file?

**Comment by jtang10** [comment]
It can be useful to save the benchmark results. In my case I need use the benchmarked results to provide some analysis and instead of copy-paste the output, a file might come in handy. However, I think here are some problems:
1. Appending to the original output file will break the existing workflow, because the output file is in a yaml format that can be directly used for the benchmarking with all the tuned output, but appending these results will just break the yaml format and make the file not useable (unless you have them appended as comment and I didn't notice).
2. Making them as csv format (or any other format that can be directly consumed) might be better.

**Comment by zhanglx13** [comment]
@yiqian1 I think Jingning's comment makes sense. Can you save the output of benchmark in another file?

**Comment by yiqian1** [comment]
Thanks for the feedback. I've changed the format of benchmark output file to CSV.

**Review by zhanglx13 — APPROVED** [review]

**Pull request merged**
