### PR TITLE
Autotune matrix_instr_nonkdim

### PR DESCRIPTION
**Pull request by htyu**
Adding `matrix_instr_nonkdim` to the autotune configs to enable tuning with different mfma shapes.

### CODE REVIEW

**Comment by zhanglx13** [comment]
@htyu Why do you need to add `matrix_instr_nonkdim` to the autotuner? Is adding it [here](https://github.com/ROCm/triton/blob/a9c0bdb96ba0294c002a29322aeda064623f87f0/python/tutorials/03-matrix-multiplication.py#L185) like `waves_per_eu` not enough?

**Comment by htyu** [comment]
> @htyu Why do you need to add `matrix_instr_nonkdim` to the autotuner? Is adding it [here](https://github.com/ROCm/triton/blob/a9c0bdb96ba0294c002a29322aeda064623f87f0/python/tutorials/03-matrix-multiplication.py#L185) like `waves_per_eu` not enough?

Oh, I didn't know about `waves_per_eu`. What does it do?  We basically want to use the 16x16 mfma instruction instead of the default 32x32 one. Can it be achieved by tuning `waves_per_eu`?

**Comment by zhanglx13** [comment]
@htyu `waves_per_eu` has nothing to do with `matrix_instr_nonkdim`. I referred to it because you can use `matrix_instr_nonkdim` (add it to kernel arg and tuning) in the same way as `waves_per_eu`. So there is no need to add it to the autotuner.

**Comment by htyu** [comment]
> @htyu `waves_per_eu` has nothing to do with `matrix_instr_nonkdim`. I referred to it because you can use `matrix_instr_nonkdim` (add it to kernel arg and tuning) in the same way as `waves_per_eu`. So there is no need to add it to the autotuner.

I see. That also works. Thanks!

**Pull request closed without merging**
